### ISSUE TITLE
Some of Services don't  work 

### ISSUE THREAD

**Issue by RuslanGlaznyov** [okp4/awesome#29]
At least these URLs don't work 
**PPNV**: 
rpc.okp.ppnv.space:36657
api.okp.ppnv.space 
https://service.ppnv.space/okp4/genesis.json
https://service.ppnv.space/okp4/addrbook.json

Same with **Nodeist**. RPC and Api don't work 
 
Can be a temporary issue.

 
Make sense to create script/github action which will check the health

**Comment by ccamel** [comment]
Thank you for bringing this to our attention, @RuslanGlaznyov. We already have a Github action that checks the availability of URLs in the README.md file:

https://github.com/okp4/awesome/blob/4076187748e50579536b4cfa575a8cf4c2b8f5cc/.github/workflows/lint.yml#L36-L50

but this check is only performed when new PRs are submitted.

We could consider something more sophisticated with regular checks but we need to consider the action that results from this (opening an issue, updating the readme file to display the status, etc.).

**Comment by RuslanGlaznyov** [comment]
we created an example for link check, how it can be updated in okp4 awsome. 
Please check it : )
https://github.com/MELLIFERA-Labs/okp4-README

---
It is just an example, but it illustrates how this can work in the current OKP4 README. 

If you are interested in that, we can create PR with this feature. Just let me know that you interested

**Comment by RuslanGlaznyov** [comment]
@ccamel

**Comment by ccamel** [comment]
He @RuslanGlaznyov. Thanks for you proposal. It's very interesting indeed, and after examining the code you've produced, we think it's just right for what we want to do. There are just a few modifications to be made to meet our CI requirements, which we can discuss before you submit the PR.

**Comment by ccamel** [comment]
@RuslanGlaznyov, I'm getting back to you with some information. 

Regarding the work you have done ([here](https://github.com/MELLIFERA-Labs/okp4-README)), I suggest submitting a Pull Request to the project. There are a few small changes that need to be made, afais:

- Move all JavaScript-related files (`index.js`, `package.json`, `package-lock.json`) to the `./github/scripts` directory.
- In the GitHub workflow, it would be appropriate to:
  - Name it `update-service-status-badges.yml`.
  - Add a manual trigger for the workflow (`workflow_dispatch`).
  - Simplify the workflow by executing the script (`node index.js`) and letting the commit action (`stefanzweifel/git-auto-commit-action`) detect whether there are changes or not.
  - Modify the commit message to `docs: update url service status badges`.

Please do not hesitate to reach out if you have any questions or need further assistance. Thank you so much for your valuable contribution to the OKP4 project.

**Comment by RuslanGlaznyov** [comment]
hello @ccamel ! Thanks you for remarks. Prepared PR https://github.com/okp4/awesome/pull/33 🙂

**Comment by ccamel** [comment]
Resolved with #33.
