### ISSUE TITLE
Reference atomscan.com - okp4-nemeton-1

### ISSUE THREAD

**Issue by ccamel** [okp4/awesome#30]
## Todo

Since PR https://github.com/cosmos/chain-registry/pull/2387 has been merged, the `okp4-nemeton-1` testnet is now listed on <https://atomscan.com/>. Let's include a reference to these resources in our *awesome* repository:

- <https://atomscan.com/directory/testnet/okp4testnet>
- <https://atomscan.com/testnet/okp4testnet>

**Comment by jeremylgn** [comment]
Here's what I suggest: 

![image](https://github.com/okp4/awesome/assets/92911731/9aad029f-8203-4969-acff-1f7297c25421)
![image](https://github.com/okp4/awesome/assets/92911731/6d8e0c0b-c74b-4ced-85a8-92b4e641d99f)

I know that @ccamel told me "`We need to see if we shouldn't split it into 2, the second being the exploration`".
Then I asked @amimart for his opinion, and he told me that "**if we put the 2 together it wouldn't make sense**".

So... what should we do ?

Thank you in advance. :pray:

**Comment by amimart** [comment]
> So... what should we do ?

I don't see the point of referencing it twice, and this is not a Ping Pub explorer as suggested :)

**Comment by ccamel** [comment]
All right. Let's do that.
