### ISSUE TITLE
README improvements

### ISSUE THREAD

**Issue by ccamel** [okp4/awesome#42]
## Purpose

I'd propose making some improvements to the `README`, listed below:

- [x] add the OKP4 banner
- [x] remove the expandable content (details/summary) to keep the content always visible. This is a matter of personal taste and also UX, but it seems more readable to me to have all the content present, without having to click to discover it.
- [x] see if the 'awesome' badge can be the same height as the other badges.
- [x] add [![PRs Welcome](https://img.shields.io/badge/PRs-welcome-brightgreen.svg?style=flat-square)](https://makeapullrequest.com) badge (see https://makeapullrequest.com/)

**Comment by jeremylgn** [comment]
Remove the expandable content (details/summary). : 
https://github.com/okp4/awesome/pull/46 :white_check_mark:
